# https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/7
dist: focal

language: node_js
node_js:
  - lts/*
  - node

install:
  - npm ci

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run release
